yaml

swagger: "2.0"
info:
  title: "User Manager API"

paths:
  /users:
    get:
      summary: "Get all users"
      responses:
        200:
          description: "Successful response"
    post:
      summary: "Create a new user"
      responses:
        200:
          description: "Successful response"

  /users/{userid}:
    get:
      summary: "Get all users"
      responses:
        200:
          description: "Successful response"

    put:
      summary: "Modify a new user"
      responses:
        200:
          description: "Successful response"

    delete:
      summary: "Delete a new user"
      responses:
        200:
          description: "Successful response"

